import requests

image_urls = [
    "https://www.windowworksnc.com/wp-content/uploads/2025/06/Window-Works.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/05/Window-Works-5.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/05/Window-Works-1.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/04/Classic-Bronze-Laminate-Endure-Mulled-Double-Hung-Windows.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/02/Endure-DH-Windows-in-Textured-Matte-Coal-Black-with-internal-grids-Endure-Cover-1.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/06/Window-Works-1-1.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/05/Window-Works-7.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/05/Window-Works.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/04/Hinged-2.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/02/8-Foot-116-Style-Legacy-Smooth-Steel_Coal-Black-e1720713398691.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/12/Long-Door-Handles.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/09/IMG_8706.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/10/Window-Works.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/08/featured-wood-door-costs.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2025/01/Feb-feature-image.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/01/featured-window-sizes.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/07/featured-windows-installed-inside-or-outside.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/08/featured-right-size-window.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/04/featured-impact-resistant-windows.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/04/featured-how-long-should-a-front-door-last.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/04/featured-pre-hung-door-is-better-than-slab.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/04/featured-door-height.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/01/featured-provia-doors.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/07/featured-multipoint-lock.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/04/featured-storm-windows.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/03/featured-resell-windows-online.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/04/featured-grille-mistakes.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/01/featured-slim-vertical-window.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/01/featured-Condensation-Outside-Your-Windows.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/01/featured-Replacing-Windows-Increase-Home-Value.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/01/featured-cladding-on-a-window.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/11/featured-bad-money-saving-tips-for-windows.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/01/featured-pet-door.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/01/featured-interior-dutch.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2024/01/featured-maintain-multipoint-lock-door.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/07/featured-thermal-break.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/02/featured-season-for-door-replacement.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/10/featured-updated-energy-star.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/07/featured-pass-through.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/05/featured-bad-installation.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/04/featured-double-hung.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/11/featured-install-own-Andersen-windows.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/07/featured-door-hardware.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/08/featured-prefinished-door.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/08/featured-doors-cost-so-much.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/07/featured-multipoint-lock.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/04/featured-love-dsa.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/01/featured-patio-door-built-in-blinds.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/01/feature-arch-top-round-top-front-door.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/06/featured-sidelights-and-transoms.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/04/featured-energy-windows-new-construction.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/04/featured-rookie-assumptions.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/01/featured-window-measure-appointment.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/02/featured-japandi.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/06/featured-window-warranty.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/06/featured-researching-windows.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/06/featured-full-frame-versus-insert-replacement-windows.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/06/featured-2023-door-trends.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/06/featured-ADA-Compliant-door.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2023/02/featured-door-security.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/06/featured-replacing-window-with-door.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/06/featured-bad-window-design.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/06/featured-brickmould.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/05/featured-3-scary-things-.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/05/featured-replace-some-of-your-windows.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/05/featured-rookie-assumptions.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/07/featured-vinyl-features.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/03/featured-windows-so-expensive.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/05/featured-historic-home-door.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/05/featured-dutch.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/08/featured-dont-do-to-front-door.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/05/featured-door-checklist.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/02/sliding-glass-door-features.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/02/door-parts-featured.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/02/dont-diy-your-door-featured.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/02/patio-door-featured-.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2021/11/Fiberglass-Door-Reeb.png",
    "https://www.windowworksnc.com/wp-content/uploads/2022/02/do-i-have-aw-features.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2021/11/Copy-of-3Window-ZoomedOut-Edited-Finish-1-1024x671.png",
    "https://www.windowworksnc.com/wp-content/uploads/2022/01/E-Series_Double-Hung_Windows_15385.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/03/andersen-versus-renewal-featured.png",
    "https://www.windowworksnc.com/wp-content/uploads/2021/12/seal-failure-image.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2021/11/400_Series_Tilt-Wash_Double-Hung_Windows_16815.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2021/08/Copy-of-B-9-scaled.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2022/02/panoramic-pic-e1641780100976.jpg",
    "https://www.windowworksnc.com/wp-content/uploads/2021/11/Springline_Entranceway_5369.jpg"
]

def check_url(url):
    try:
        response = requests.head(url, allow_redirects=True, timeout=5)
        if response.status_code == 404:
            return False
        return True
    except requests.RequestException:
        return False

if __name__ == "__main__":
    for url in image_urls:
        exists = check_url(url)
        print(f"{url} - {'OK' if exists else '404 NOT FOUND'}")